import type { Metadata } from "next";
import { Inter_Tight, Bricolage_Grotesque } from "next/font/google";
import "./globals.css";

import { TwScreenSize } from "@/components/ui/tw-utils";

const interTight = Inter_Tight({
  variable: "--font-inter-tight-sans",
  subsets: ["latin"],
});

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sugo Coin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interTight.className} ${bricolageGrotesque.variable} antialiased`}
      >
        {children}
        <TwScreenSize />
      </body>
    </html>
  );
}
